### PR TITLE
Cleaning up the template

### PR DESCRIPTION
**Pull request by ghost**
#1: Moved copyTemp task to 'build' because it's much clearer
#2: install for packaging into build not build/www (again it's clearer)
#3: removing example code in web/
#3 is the only controversial change, which I'm suggesting because I think it makes more sense to do this than have code in web that makes it less clear which is template vs which is app, but I'm open to debate.

### CODE REVIEW

**Comment by yaronyg** [comment]
In regards to point 3 I have several concerns:

Concern 1 - For a Thali app to work it needs at least 2 or 3 (depending on how we package things) JS files from us. This includes our version of PouchDB that we have tested against and know works as well as our PouchDB HttpKeyURL adapter as well as the code that handles loading the relay proxy location and shared secrets. So we will have files in web and the user needs to keep those files or their app won't work. So web can't be empty.

Concern 2 - I can't tell you how many projects I've seen (including Thali Android) that began life with the platform sample app and then grew as it was changed line by line. So I really think it's important to ship with a simple 'hello world' style app that shows some basic functionality (which, btw, the Pouch tests do) so that people can use that as a base to jump off from. I do agree that we should make the sample app better but it's still a good starting point.

Concern 3 - Until we have those 'test' things having the sample app makes life much easier as a dev working on the seed because I can just run the seed and see if it still works.

What do you say?

**Comment by ghost** [comment]
I’m entirely willing to put these files back into the app, but I think the distinction between git and github isn’t quite as clear to me as it is to you. Multiple clones of a repo overwrite each other, multiple forks do not. So I’m not sure what workflow you are describing and how it supports developing > 1 Thali app, but I’m comfortable crossing that bridge when we get to it – have a developer build 1 app is a win right now.

--Ivan

**Comment by yaronyg** [comment]
The work flow I would imagine is, assuming the dev is using GitHub,
1. Hit the big green "+ New respository" button on the front page of GitHub.
2. Set up license and the hello world file.
3. Clone the new repository to their machine
4. On their local machine issue 'git remote add upstream https://github.com/thaliproject/ThaliHTML5ApplicationFramework.git'
5. Also on their local machine issue 'git fetch upstream'
6. Then 'git merge upstream/master'
7. Then 'git mergetool' if there are conflicts on things like the license file

Now they have a stand alone Git Repo that they can build their code in the web directory. If they want to take newer bits from the ThaliHTML5ApplicationFramework then they just repeat steps 5-7 above.

If they keep their content in web/src/js then the only files we should touch in there are our sample files. The only thing I'm not sure of is what happens when we update a file they have deleted (like pouchdb_test.js). I think that just works but if we are wrong we can figure something out. At worst they can just leave our test files alone and not reference them.

**Comment by ghost** [comment]
I've reverted _most_ of the changes -- I left the build targets and inclusion of node 'express' so local application testing is possible.

**Comment by ghost** [comment]
I disagree. The typical OSS / Github flow is (this has been my experience for > 30 repos since 2008, fwiw):

1)      Fork repo

2)      Hack your code

3)      Push to your repo or release to a public place to share artifacts (gems for ruby, packages for python, apps to stores, etc)

4)      If it’s useful for the origin, make a PR

This is what I expect developers both to do and to be able to do – nobody manually fusses with remotes – if you fork upstream is set automatically –

If we don’t hit this target, I fear we’ve created a huge barrier to entry for new developers.

--Ivan

**Comment by yaronyg** [comment]
And that approach works just fine for your first app. It's your second where you run into trouble because GitHub, as far as I know, won't let you fork a repo twice.

The alternative is to try to build multiple independent apps in the same repro using branches and nobody I know would do that either. 1 App == 1 Repo.

This, btw, is why having source code dependencies is such a spectacularly bad idea. The right way for this repro to work is like CrossWalk. We become a binary that people call to do the build and that's it. Zero source code dependency. But first we have to crawl before we can walk or run.

**Comment by ghost** [comment]
This was why I separated the repositories, with the idea that the HTML5ApplicationFramework should eventually be replaced by a binary-ish tool you run on your application (which is it’s own repo).

Then we don’t care, we provide the application-seed, they fork and modify (which includes our dependencies like pouch, etc) and then they run our tool to “package” it for Thali.

That feels much more like the intent we’ve talked about … doesn’t it?

--Ivan

**Comment by yaronyg** [comment]
I wonder if we have a terminology issue here. 

In my head the HTML5ApplicationFramework == seed.

Your text reads like you see these as separate. There is the Framework which, like XWalk, would come with no code. Then there is the 'seed' which is just a sample Thali HTML5 app?

If that is the case wouldn't the Framework come down as a binary (e.g. no github) and the 'seed' just be a sample file up on our website (again, no github)?

I'm just trying to figure out if we are using the same words to mean the same thing.

**Comment by ghost** [comment]
There is a terminology issue, but here’s my definition list:

1)      The tool used to package generic HTML5 applications as Thali apps  - this has no name, I refer to this as the HTML5ApplicationFramework

2)      A template application that developers can copy and modify – this has no name, and exists entirely in my account as the thali-addressbook for now, but this is the real intent of a seed. It should be replaced with the puton based, thali data browser that shows how to communicate via thali.

I believe it makes less sense to make #1 part of #2 if we’re going to rip it out and package it separately – in any reasonable timeframe, but if we’re not going to, it should be as loosely coupled to #2 as possible, which is why I like the model:

1)      _clone_ not fork, ThaliHTML5ApplicationFramework

2)      cd ThaliHTML5ApplicationFramework/web

3)      git clone thali-seed (or my repo, or whatever)

4)      Hack on my app, push modifications to my rep

5)      cd .. (to ThaliHTML5ApplicationFramework)

6)      ./gradlew.bat buildApp

This is a pretty simple workflow that’s understandable and we can simplify later when we make the ThaliHTML5ApplicationFramework a tool, not a repo.

Does that make sense?

--Ivan

**Comment by yaronyg** [comment]
Per our conversation we will keep the web files in the project until we finally have the app building code running as a stand alone binary and then we will create a new repo just with the sample files and necessary JS supporting libraries (e.g. for our pouch adapter, relay discovery, etc.)

**Pull request merged**
